### ISSUE TITLE
Example code fails to compile

### ISSUE THREAD

**Issue by dragos** [cvogt/cbt#495]
Following the README, I tried

```
$ cbt eval 'sources.strings.mkString(":")'
cbt.eval.Eval$CompilerException: Compiler exception error: line 4: value strings is not a member of Seq[java.io.File]
        println{ sources.strings.mkString(":") }
                         ^
	at cbt.eval.Eval$StringCompiler.apply(Eval.scala:610)
	at cbt.eval.Eval.compile(Eval.scala:222)
	at cbt.DynamicOverrides$class.newBuild(DynamicOverrides.scala:75)
	at dragos_vscode_scala_build.Build.newBuild(build.scala:3)
...
```

**Comment by cvogt** [comment]
thx. fix in https://github.com/cvogt/cbt/pull/500
