### ISSUE TITLE
NumberFormatException when running cbt in direct mode

### ISSUE THREAD

**Issue by darthorimar** [cvogt/cbt#593]
Getting `NumberFormatException` when running `cbt direct run` after code changes. Have not got this error before
```
$ cbt direct run
Compiling to /home/ilya/playground/cbtException/target/scala-2.11/classes
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
	at jline.UnixTerminal.<init>(UnixTerminal.java:64)
	at jline.UnixTerminal.<init>(UnixTerminal.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
	at jline.TerminalFactory.create(TerminalFactory.java:100)
	at jline.TerminalFactory.get(TerminalFactory.java:184)
	at jline.TerminalFactory.get(TerminalFactory.java:190)
	at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
	at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
	at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	at com.typesafe.zinc.Util$.logger(Util.scala:23)
	at com.typesafe.zinc.Main$.run(Main.scala:31)
	at com.typesafe.zinc.Main$.main(Main.scala:15)
	at com.typesafe.zinc.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cbt.reflect.Module$$anonfun$typeStaticMethod$1$$anonfun$apply$6.apply(reflect.scala:170)
	at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1$$anonfun$apply$2.apply(reflect.scala:121)
	at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1$$anonfun$apply$2.apply(reflect.scala:121)
	at cbt.reflect.Module$$anon$1.run(reflect.scala:178)
	at cbt.reflect.Module$$anon$1.run(reflect.scala:177)
	at cbt.reflect.TrapSystemExit.run(TrapSystemExit.java:15)
	at cbt.reflect.Module$class.trapExitCodeOrValue(reflect.scala:176)
	at cbt.Stage1Lib.trapExitCodeOrValue(Stage1Lib.scala:14)
	at cbt.reflect.Module$class.trapExitCode(reflect.scala:185)
	at cbt.Stage1Lib.trapExitCode(Stage1Lib.scala:14)
	at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1.apply(reflect.scala:121)
	at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1.apply(reflect.scala:121)
	at cbt.reflect.Module$$anonfun$getMain$1.apply(reflect.scala:70)
	at cbt.reflect.Module$$anonfun$getMain$1.apply(reflect.scala:70)
	at cbt.reflect.StaticMethod.apply(StaticMethod.scala:4)
	at cbt.DependencyImplementation$class.runMain(resolver.scala:82)
	at cbt.BoundMavenDependency.runMain(resolver.scala:236)
	at cbt.Stage1Lib$$anonfun$9.apply(Stage1Lib.scala:207)
	at cbt.Stage1Lib$$anonfun$9.apply(Stage1Lib.scala:204)
	at cbt.Stage1Lib.redirectOutToErr(Stage1Lib.scala:286)
	at cbt.Stage1Lib.compile(Stage1Lib.scala:204)
	at cbt.BaseBuild$$anonfun$compile$1.apply(BasicBuild.scala:168)
	at cbt.BaseBuild$$anonfun$compile$1.apply(BasicBuild.scala:168)
	at cbt.PerClassCache$MethodCache.memoize(Stage1Lib.scala:464)
	at cbt.BaseBuild$class.compile(BasicBuild.scala:167)
	at bb_build.Build.compile(build.scala:3)
	at cbt.BaseBuild$class.exportedClasspath(BasicBuild.scala:144)
	at bb_build.Build.exportedClasspath(build.scala:3)
	at cbt.DependencyImplementation$class.classes(resolver.scala:96)
	at bb_build.Build.classes(build.scala:3)
	at cbt.DependencyImplementation$class.mainClass(resolver.scala:93)
	at bb_build.Build.mainClass(build.scala:3)
	at cbt.DependencyImplementation$class.mainClassOrFail(resolver.scala:87)
	at bb_build.Build.mainClassOrFail(build.scala:3)
	at cbt.DependencyImplementation$class.runMain(resolver.scala:85)
	at bb_build.Build.runMain(build.scala:3)
	at cbt.BaseBuild$class.run(BasicBuild.scala:217)
	at bb_build.Build.run(build.scala:3)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11$$anonfun$apply$12.apply(Lib.scala:155)
	at cbt.reflect.Module$$anon$1.run(reflect.scala:178)
	at cbt.reflect.Module$$anon$1.run(reflect.scala:177)
	at cbt.reflect.TrapSystemExit.run(TrapSystemExit.java:15)
	at cbt.reflect.Module$class.trapExitCodeOrValue(reflect.scala:176)
	at cbt.Stage1Lib.trapExitCodeOrValue(Stage1Lib.scala:14)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11.apply(Lib.scala:155)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11.apply(Lib.scala:153)
	at scala.Option.map(Option.scala:146)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9.apply(Lib.scala:153)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9.apply(Lib.scala:150)
	at scala.Option.map(Option.scala:146)
	at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1.apply(Lib.scala:150)
	at cbt.Lib$$anonfun$3.cbt$Lib$$anonfun$$g$1(Lib.scala:103)
	at cbt.Lib$$anonfun$3$$anonfun$apply$5.apply(Lib.scala:105)
	at cbt.Lib.cbt$Lib$$callInternal(Lib.scala:175)
	at cbt.Lib.getReflective(Lib.scala:143)
	at cbt.Lib.callReflective(Lib.scala:106)
	at cbt.Stage2$.run(Stage2.scala:35)
	at cbt.Stage2.run(Stage2.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cbt.Stage1$.run(Stage1.scala:210)
	at cbt.Stage1.run(Stage1.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cbt.NailgunLauncher.main(NailgunLauncher.java:123)
```

**Comment by jendrikw** [comment]
This looks like jline/jline2#281, which was fixed in jline 2.14.4.
